// Progression levels up to Level 50
export const PROGRESSION_LEVELS = [
  { level: 1, name: "Beginner Saver", xpRequired: 0, icon: "🌱", color: "from-green-500 to-emerald-600", reward: "Apprentice Badge & 'Novice' Title" },
  { level: 2, name: "Daily Tracker", xpRequired: 500, icon: "📒", color: "from-blue-500 to-indigo-600", reward: "+50 Coins & 'Tracker' Title" },
  { level: 3, name: "Smart Spender", xpRequired: 1200, icon: "💰", color: "from-emerald-500 to-teal-600", reward: "Copper Avatar Frame & 'Thrifty' Sticker" },
  { level: 4, name: "Budget Builder", xpRequired: 2200, icon: "🧱", color: "from-amber-500 to-yellow-600", reward: "+100 Coins & 'Budgeter' Title" },
  { level: 5, name: "Habit Master", xpRequired: 3500, icon: "🔁", color: "from-orange-500 to-red-600", reward: "Silver Avatar Frame & 'Consistent' Sticker" },
  { level: 6, name: "Frugal Finder", xpRequired: 5000, icon: "🔍", color: "from-violet-500 to-purple-600", reward: "+150 Coins & 'Frugal' Title" },
  { level: 7, name: "Compound Creator", xpRequired: 7000, icon: "📈", color: "from-indigo-500 to-sky-600", reward: "Investment Theme & 'Investor' Badge" },
  { level: 8, name: "Goal Getter", xpRequired: 9500, icon: "🎯", color: "from-rose-500 to-pink-600", reward: "+200 Coins & 'Goal Getter' Title" },
  { level: 9, name: "Expense Auditor", xpRequired: 12500, icon: "🕵️", color: "from-cyan-500 to-teal-600", reward: "Audit Sticker & 'Auditor' Title" },
  { level: 10, name: "Wealth Initiate", xpRequired: 16000, icon: "💎", color: "from-teal-500 to-emerald-600", reward: "Gold Avatar Frame & 'Wealthy' Badge" },
  { level: 11, name: "Carbon Reducer", xpRequired: 20000, icon: "🍃", color: "from-lime-500 to-green-600", reward: "+250 Coins & 'Eco Guardian' Theme" },
  { level: 12, name: "Interest Accumulator", xpRequired: 25000, icon: "🪙", color: "from-yellow-500 to-amber-600", reward: "Interest Calculator Widget & 'Saver Pro' Title" },
  { level: 13, name: "Portfolio Architect", xpRequired: 31000, icon: "📂", color: "from-sky-500 to-blue-600", reward: "Premium Portfolio Theme & 'Architect' Badge" },
  { level: 14, name: "Dividend Baron", xpRequired: 38000, icon: "👑", color: "from-fuchsia-500 to-purple-600", reward: "+300 Coins & 'Baron' Title" },
  { level: 15, name: "Financial Ninja", xpRequired: 46000, icon: "🥷", color: "from-red-500 to-rose-600", reward: "Dark Mode Ninja Theme & Ninja Avatar Frame" }
];

// XP rewards for actions
export const XP_ACTIONS = [
  { id: "login", label: "Daily Login", xp: 100, coins: 10 },
  { id: "add_expense", label: "Add Expense", xp: 50, coins: 5 },
  { id: "add_income", label: "Add Income", xp: 50, coins: 5 },
  { id: "upload_receipt", label: "Upload Receipt", xp: 150, coins: 15 },
  { id: "create_budget", label: "Create Budget", xp: 200, coins: 20 },
  { id: "stay_daily_budget", label: "Stay Within Daily Budget", xp: 100, coins: 10 },
  { id: "stay_weekly_budget", label: "Stay Within Weekly Budget", xp: 300, coins: 30 },
  { id: "stay_monthly_budget", label: "Stay Within Monthly Budget", xp: 1000, coins: 100 },
  { id: "complete_review", label: "Complete Monthly Review", xp: 500, coins: 50 },
  { id: "add_goal", label: "Add Savings Goal", xp: 150, coins: 15 },
  { id: "reach_goal", label: "Reach Savings Goal", xp: 1000, coins: 100 },
  { id: "add_investment", label: "Add Investment", xp: 300, coins: 30 },
  { id: "track_bills", label: "Track Bills", xp: 100, coins: 10 },
  { id: "pay_bills_on_time", label: "Pay Bills On Time", xp: 250, coins: 25 },
  { id: "categorize_expense", label: "Categorize Expense", xp: 40, coins: 4 },
  { id: "export_reports", label: "Export Reports", xp: 200, coins: 20 },
  { id: "view_analytics", label: "View Analytics", xp: 75, coins: 7 },
  { id: "maintain_streak", label: "Maintain Daily Streak (+1 Day)", xp: 150, coins: 15 },
  { id: "invite_friends", label: "Invite Friends", xp: 500, coins: 50 },
  { id: "backup_data", label: "Backup Data", xp: 100, coins: 10 }
];

// Expanded Achievements (100+ items across 10 categories)
export const INITIAL_ACHIEVEMENTS = [
  // ─── CATEGORY 1: SAVINGS (11 achievements) ───
  { id: "s1", title: "First Piggy Deposit", description: "Logged your first savings deposit", requirement: "Add 1 goal deposit", xpReward: 100, coinsReward: 10, icon: "🐖", category: "Savings", tier: "Common", progressNeeded: 1, currentProgress: 0, unlocked: false },
  { id: "s2", title: "Goal Setter", description: "Created your first savings goal", requirement: "Create 1 goal", xpReward: 150, coinsReward: 15, icon: "🎯", category: "Savings", tier: "Common", progressNeeded: 1, currentProgress: 0, unlocked: false },
  { id: "s3", title: "Double Down Savings", description: "Save at least ₹2,000 in any goal", requirement: "Deposit ₹2,000", xpReward: 200, coinsReward: 20, icon: "🪙", category: "Savings", tier: "Common", progressNeeded: 2000, currentProgress: 0, unlocked: false },
  { id: "s4", title: "Milestone Achiever", description: "Fully completed one savings goal", requirement: "Complete 1 goal", xpReward: 500, coinsReward: 50, icon: "🏆", category: "Savings", tier: "Rare", progressNeeded: 1, currentProgress: 0, unlocked: false },
  { id: "s5", title: "Tenacious Saver", description: "Deposited into savings goals 5 times", requirement: "Make 5 deposits", xpReward: 300, coinsReward: 30, icon: "🗳️", category: "Savings", tier: "Common", progressNeeded: 5, currentProgress: 0, unlocked: false },
  { id: "s6", title: "Emergency Shield", description: "Create an Emergency Fund goal", requirement: "Create Emergency Goal", xpReward: 200, coinsReward: 20, icon: "🛡️", category: "Savings", tier: "Common", progressNeeded: 1, currentProgress: 0, unlocked: false },
  { id: "s7", title: "Halfway Heaven", description: "Reach 50% completion on a major goal", requirement: "Reach 50% goal", xpReward: 350, coinsReward: 35, icon: "⛅", category: "Savings", tier: "Rare", progressNeeded: 50, currentProgress: 0, unlocked: false },
  { id: "s8", title: "Savings Stack", description: "Save a cumulative total of ₹10,000", requirement: "Save ₹10,000 total", xpReward: 600, coinsReward: 60, icon: "📚", category: "Savings", tier: "Rare", progressNeeded: 10000, currentProgress: 0, unlocked: false },
  { id: "s9", title: "Accumulator Pro", description: "Save a cumulative total of ₹50,000", requirement: "Save ₹50,000 total", xpReward: 1200, coinsReward: 120, icon: "💎", category: "Savings", tier: "Epic", progressNeeded: 50000, currentProgress: 0, unlocked: false },
  { id: "s10", title: "Sovereign Vault", description: "Save a cumulative total of ₹2,00,000", requirement: "Save ₹2,00,000 total", xpReward: 3000, coinsReward: 300, icon: "🏛️", category: "Savings", tier: "Legendary", progressNeeded: 200000, currentProgress: 0, unlocked: false },
  { id: "s11", title: "Double Victory", description: "Complete 2 savings goals in the same month", requirement: "Complete 2 goals", xpReward: 1000, coinsReward: 100, icon: "✨", category: "Savings", tier: "Epic", progressNeeded: 2, currentProgress: 0, unlocked: false },

  // ─── CATEGORY 2: BUDGET (11 achievements) ───
  { id: "b1", title: "Budget Architect", description: "Created your first budget limit", requirement: "Create 1 budget", xpReward: 100, coinsReward: 10, icon: "🧱", category: "Budget", tier: "Common", progressNeeded: 1, currentProgress: 0, unlocked: false },
  { id: "b2", title: "Safety Net", description: "Configure an alert threshold for budget limits", requirement: "Set alert threshold", xpReward: 150, coinsReward: 15, icon: "🔔", category: "Budget", tier: "Common", progressNeeded: 1, currentProgress: 0, unlocked: false },
  { id: "b3", title: "Disciplined Week", description: "Stay under budget in all categories for 7 days", requirement: "Stay under budget 7d", xpReward: 300, coinsReward: 30, icon: "📅", category: "Budget", tier: "Rare", progressNeeded: 7, currentProgress: 0, unlocked: false },
  { id: "b4", title: "Frugal Fortnight", description: "Stay under budget in all categories for 14 days", requirement: "Stay under budget 14d", xpReward: 500, coinsReward: 50, icon: "🎖️", category: "Budget", tier: "Rare", progressNeeded: 14, currentProgress: 0, unlocked: false },
  { id: "b5", title: "Budget Shield", description: "Do not exceed budget in any category for 30 days", requirement: "Stay under budget 30d", xpReward: 1000, coinsReward: 100, icon: "🛡️", category: "Budget", tier: "Epic", progressNeeded: 30, currentProgress: 0, unlocked: false },
  { id: "b6", title: "Expense Cap Pro", description: "Create 5 distinct category budgets", requirement: "Create 5 budgets", xpReward: 400, coinsReward: 40, icon: "📁", category: "Budget", tier: "Rare", progressNeeded: 5, currentProgress: 0, unlocked: false },
  { id: "b7", title: "Category Guard", description: "Keep Food & Dining under budget for a month", requirement: "Under budget Food 30d", xpReward: 300, coinsReward: 30, icon: "🍔", category: "Budget", tier: "Common", progressNeeded: 30, currentProgress: 0, unlocked: false },
  { id: "b8", title: "Zero Variance", description: "End a week with spending equal to budget limits", requirement: "Equal budget week", xpReward: 800, coinsReward: 80, icon: "🎯", category: "Budget", tier: "Rare", progressNeeded: 1, currentProgress: 0, unlocked: false },
  { id: "b9", title: "Budget Mastermind", description: "Spend less than 80% of total budget limit in a month", requirement: "Spend < 80% limit", xpReward: 1200, coinsReward: 120, icon: "👑", category: "Budget", tier: "Epic", progressNeeded: 1, currentProgress: 0, unlocked: false },
  { id: "b10", title: "Budget Grandmaster", description: "Keep spending within limits for 3 months straight", requirement: "Keep limits 90d", xpReward: 2500, coinsReward: 250, icon: "🔮", category: "Budget", tier: "Legendary", progressNeeded: 90, currentProgress: 0, unlocked: false },
  { id: "b11", title: "Savings Boost", description: "Increase your budget limits due to income raises", requirement: "Adjust budgets", xpReward: 200, coinsReward: 20, icon: "📈", category: "Budget", tier: "Common", progressNeeded: 1, currentProgress: 0, unlocked: false },

  // ─── CATEGORY 3: INVESTMENT (11 achievements) ───
  { id: "i1", title: "First Asset", description: "Logged your first investment purchase", requirement: "Add 1 investment", xpReward: 150, coinsReward: 15, icon: "📊", category: "Investment", tier: "Common", progressNeeded: 1, currentProgress: 0, unlocked: false },
  { id: "i2", title: "Fund Allocator", description: "Invest in a Mutual Index Fund", requirement: "Add Mutual Fund", xpReward: 200, coinsReward: 20, icon: "📈", category: "Investment", tier: "Common", progressNeeded: 1, currentProgress: 0, unlocked: false },
  { id: "i3", title: "Crypto Pioneer", description: "Log a cryptocurrency asset", requirement: "Add Crypto", xpReward: 250, coinsReward: 25, icon: "🪙", category: "Investment", tier: "Common", progressNeeded: 1, currentProgress: 0, unlocked: false },
  { id: "i4", title: "Gold Standard", description: "Log a Gold/Sovereign Gold investment", requirement: "Add Gold asset", xpReward: 200, coinsReward: 20, icon: "👑", category: "Investment", tier: "Common", progressNeeded: 1, currentProgress: 0, unlocked: false },
  { id: "i5", title: "Pension Builder", description: "Invest in NPS or PPF retirement tools", requirement: "Add NPS/PPF log", xpReward: 300, coinsReward: 30, icon: "🛡️", category: "Investment", tier: "Rare", progressNeeded: 1, currentProgress: 0, unlocked: false },
  { id: "i6", title: "Asset Diversifier", description: "Hold at least 3 distinct types of assets", requirement: "Own 3 asset types", xpReward: 500, coinsReward: 50, icon: "🧩", category: "Investment", tier: "Rare", progressNeeded: 3, currentProgress: 0, unlocked: false },
  { id: "i7", title: "Portfolio Builder", description: "Invest a total of ₹10,000", requirement: "Invest ₹10,000", xpReward: 400, coinsReward: 40, icon: "💼", category: "Investment", tier: "Common", progressNeeded: 10000, currentProgress: 0, unlocked: false },
  { id: "i8", title: "Asset Heavyweight", description: "Invest a total of ₹50,000", requirement: "Invest ₹50,000", xpReward: 1000, coinsReward: 100, icon: "💎", category: "Investment", tier: "Rare", progressNeeded: 50000, currentProgress: 0, unlocked: false },
  { id: "i9", title: "Capital Emperor", description: "Invest a total of ₹2,50,000", requirement: "Invest ₹2,50,000", xpReward: 2500, coinsReward: 250, icon: "🏛️", category: "Investment", tier: "Epic", progressNeeded: 250000, currentProgress: 0, unlocked: false },
  { id: "i10", title: "Green Returns", description: "Generate a profit return on your assets", requirement: "Positive investment return", xpReward: 600, coinsReward: 60, icon: "🟢", category: "Investment", tier: "Rare", progressNeeded: 1, currentProgress: 0, unlocked: false },
  { id: "i11", title: "Compound King", description: "Keep investments untouched for 30 days", requirement: "Hold assets 30d", xpReward: 800, coinsReward: 80, icon: "🏦", category: "Investment", tier: "Rare", progressNeeded: 30, currentProgress: 0, unlocked: false },

  // ─── CATEGORY 4: CONSISTENCY (11 achievements) ───
  { id: "c1", title: "Hello World", description: "Logged in on your first day", requirement: "Daily login", xpReward: 50, coinsReward: 5, icon: "👋", category: "Consistency", tier: "Common", progressNeeded: 1, currentProgress: 0, unlocked: false },
  { id: "c2", title: "Log Spark", description: "Maintain a logging streak of 3 days", requirement: "Streak of 3d", xpReward: 100, coinsReward: 10, icon: "🔥", category: "Consistency", tier: "Common", progressNeeded: 3, currentProgress: 0, unlocked: false },
  { id: "c3", title: "Streak Master", description: "Maintain a logging streak of 7 days", requirement: "Streak of 7d", xpReward: 300, coinsReward: 30, icon: "⚡", category: "Consistency", tier: "Rare", progressNeeded: 7, currentProgress: 0, unlocked: false },
  { id: "c4", title: "Thrifty Month", description: "Maintain a logging streak of 30 days", requirement: "Streak of 30d", xpReward: 1000, coinsReward: 100, icon: "📆", category: "Consistency", tier: "Epic", progressNeeded: 30, currentProgress: 0, unlocked: false },
  { id: "c5", title: "Centurion Tracker", description: "Maintain a logging streak of 100 days", requirement: "Streak of 100d", xpReward: 4000, coinsReward: 400, icon: "💯", category: "Consistency", tier: "Legendary", progressNeeded: 100, currentProgress: 0, unlocked: false },
  { id: "c6", title: "Weekday Warrior", description: "Log a transaction every weekday for one week", requirement: "Mon-Fri entries", xpReward: 200, coinsReward: 20, icon: "💼", category: "Consistency", tier: "Common", progressNeeded: 5, currentProgress: 0, unlocked: false },
  { id: "c7", title: "Weekend Auditor", description: "Log a transaction every Saturday and Sunday", requirement: "Sat-Sun entries", xpReward: 200, coinsReward: 20, icon: "🍺", category: "Consistency", tier: "Common", progressNeeded: 2, currentProgress: 0, unlocked: false },
  { id: "c8", title: "Month End Closeout", description: "Perform reports review on the 30th/31st", requirement: "Review month end", xpReward: 300, coinsReward: 30, icon: "📊", category: "Consistency", tier: "Common", progressNeeded: 1, currentProgress: 0, unlocked: false },
  { id: "c9", title: "Half-Year Tracker", description: "Login for 180 distinct days", requirement: "Login 180 days", xpReward: 2000, coinsReward: 200, icon: "🏛️", category: "Consistency", tier: "Epic", progressNeeded: 180, currentProgress: 0, unlocked: false },
  { id: "c10", title: "Year-Long Ledger", description: "Login for 365 distinct days", requirement: "Login 365 days", xpReward: 5000, coinsReward: 500, icon: "👑", category: "Consistency", tier: "Legendary", progressNeeded: 365, currentProgress: 0, unlocked: false },
  { id: "c11", title: "Daily Habit", description: "Log at least 3 transactions per day", requirement: "Log 3 entries in a day", xpReward: 150, coinsReward: 15, icon: "✍️", category: "Consistency", tier: "Common", progressNeeded: 3, currentProgress: 0, unlocked: false },

  // ─── CATEGORY 5: AI (11 achievements) ───
  { id: "a1", title: "AI Hello", description: "Ask your first question in the AI Chatbot page", requirement: "Send AI message", xpReward: 100, coinsReward: 10, icon: "🤖", category: "AI", tier: "Common", progressNeeded: 1, currentProgress: 0, unlocked: false },
  { id: "a2", title: "Spend Predictor", description: "Ask the AI assistant to predict future spending", requirement: "Ask about spend prediction", xpReward: 200, coinsReward: 20, icon: "🔮", category: "AI", tier: "Common", progressNeeded: 1, currentProgress: 0, unlocked: false },
  { id: "a3", title: "Savings Consultant", description: "Ask the AI assistant what you should save", requirement: "Ask about saving rate", xpReward: 200, coinsReward: 20, icon: "💰", category: "AI", tier: "Common", progressNeeded: 1, currentProgress: 0, unlocked: false },
  { id: "a4", title: "Budget Recommendation", description: "Ask the AI to recommend custom category budgets", requirement: "Ask budget advice", xpReward: 200, coinsReward: 20, icon: "🧱", category: "AI", tier: "Common", progressNeeded: 1, currentProgress: 0, unlocked: false },
  { id: "a5", title: "Chart Interpreter", description: "Ask the AI chatbot to explain your reports", requirement: "Ask chart explanation", xpReward: 300, coinsReward: 30, icon: "📊", category: "AI", tier: "Rare", progressNeeded: 1, currentProgress: 0, unlocked: false },
  { id: "a6", title: "Conversationalist", description: "Exchange 10 messages with the AI assistant", requirement: "10 chat messages", xpReward: 300, coinsReward: 30, icon: "🗣️", category: "AI", tier: "Common", progressNeeded: 10, currentProgress: 0, unlocked: false },
  { id: "a7", title: "Scholar of Tips", description: "Read the AI Tip of the Day 5 times", requirement: "Read AI tips", xpReward: 250, coinsReward: 25, icon: "💡", category: "AI", tier: "Common", progressNeeded: 5, currentProgress: 0, unlocked: false },
  { id: "a8", title: "Expense Critic", description: "Ask the AI to detect unnecessary expenses", requirement: "Ask for leakage audit", xpReward: 300, coinsReward: 30, icon: "🕵️", category: "AI", tier: "Rare", progressNeeded: 1, currentProgress: 0, unlocked: false },
  { id: "a9", title: "Financial Summary Request", description: "Request a monthly financial summary from AI", requirement: "Ask for summary", xpReward: 450, coinsReward: 45, icon: "📄", category: "AI", tier: "Rare", progressNeeded: 1, currentProgress: 0, unlocked: false },
  { id: "a10", title: "AI Whisperer", description: "Utilize all AI assistant commands at least once", requirement: "Complete all AI commands", xpReward: 1000, coinsReward: 100, icon: "🌀", category: "AI", tier: "Epic", progressNeeded: 5, currentProgress: 0, unlocked: false },
  { id: "a11", title: "Smart Budget Advice", description: "Implement a budget category recommended by AI", requirement: "Create AI budget", xpReward: 500, coinsReward: 50, icon: "✅", category: "AI", tier: "Rare", progressNeeded: 1, currentProgress: 0, unlocked: false },

  // ─── CATEGORY 6: SECURITY (11 achievements) ───
  { id: "sec1", title: "Lock & Key", description: "Update your account password", requirement: "Change password", xpReward: 100, coinsReward: 10, icon: "🔑", category: "Security", tier: "Common", progressNeeded: 1, currentProgress: 0, unlocked: false },
  { id: "sec2", title: "Fortress Guard", description: "Enable Two-Factor Authentication (OTP)", requirement: "Enable 2FA", xpReward: 500, coinsReward: 50, icon: "🛡️", category: "Security", tier: "Rare", progressNeeded: 1, currentProgress: 0, unlocked: false },
  { id: "sec3", title: "MFA Enforcer", description: "Verify account using OTP code", requirement: "Verify OTP code", xpReward: 300, coinsReward: 30, icon: "📲", category: "Security", tier: "Rare", progressNeeded: 1, currentProgress: 0, unlocked: false },
  { id: "sec4", title: "Emergency Code Access", description: "Generate and save 2FA Backup Codes", requirement: "Generate backup codes", xpReward: 200, coinsReward: 20, icon: "📝", category: "Security", tier: "Common", progressNeeded: 1, currentProgress: 0, unlocked: false },
  { id: "sec5", title: "Device Auditor", description: "Inspect active device login history", requirement: "View login history", xpReward: 150, coinsReward: 15, icon: "💻", category: "Security", tier: "Common", progressNeeded: 1, currentProgress: 0, unlocked: false },
  { id: "sec6", title: "Session Manager", description: "Revoke another active login session", requirement: "Revoke device session", xpReward: 300, coinsReward: 30, icon: "🚫", category: "Security", tier: "Rare", progressNeeded: 1, currentProgress: 0, unlocked: false },
  { id: "sec7", title: "Audit Trail Specialist", description: "Review security logs history logs", requirement: "Read security logs", xpReward: 200, coinsReward: 20, icon: "📜", category: "Security", tier: "Common", progressNeeded: 1, currentProgress: 0, unlocked: false },
  { id: "sec8", title: "Safety Patrol", description: "Log out of app on a session manually", requirement: "Manual logout", xpReward: 100, coinsReward: 10, icon: "🚪", category: "Security", tier: "Common", progressNeeded: 1, currentProgress: 0, unlocked: false },
  { id: "sec9", title: "MFA Verified Login", description: "Successfully login with 2FA active", requirement: "2FA log in", xpReward: 400, coinsReward: 40, icon: "🔒", category: "Security", tier: "Rare", progressNeeded: 1, currentProgress: 0, unlocked: false },
  { id: "sec10", title: "Ultimate Shield", description: "Keep account locked and clean for 90 days", requirement: "Clean security 90d", xpReward: 1500, coinsReward: 150, icon: "💎", category: "Security", tier: "Epic", progressNeeded: 90, currentProgress: 0, unlocked: false },
  { id: "sec11", title: "Identity Lock", description: "Setup OAuth social authentication links", requirement: "Link Google/Github", xpReward: 300, coinsReward: 30, icon: "🌐", category: "Security", tier: "Rare", progressNeeded: 1, currentProgress: 0, unlocked: false },

  // ─── CATEGORY 7: PRODUCTIVITY (10 achievements) ───
  { id: "p1", title: "Documenter", description: "Export financial reports to CSV format", requirement: "Export CSV", xpReward: 150, coinsReward: 15, icon: "📄", category: "Productivity", tier: "Common", progressNeeded: 1, currentProgress: 0, unlocked: false },
  { id: "p2", title: "Spreadsheet Geek", description: "Export financial reports to Excel format", requirement: "Export Excel", xpReward: 150, coinsReward: 15, icon: "📊", category: "Productivity", tier: "Common", progressNeeded: 1, currentProgress: 0, unlocked: false },
  { id: "p3", title: "PDF Printer", description: "Print or export reports to PDF format", requirement: "Export PDF", xpReward: 150, coinsReward: 15, icon: "📑", category: "Productivity", tier: "Common", progressNeeded: 1, currentProgress: 0, unlocked: false },
  { id: "p4", title: "OCR Tech", description: "Upload a receipt and perform mock OCR extraction", requirement: "OCR receipt scan", xpReward: 300, coinsReward: 30, icon: "📷", category: "Productivity", tier: "Rare", progressNeeded: 1, currentProgress: 0, unlocked: false },
  { id: "p6", title: "Widget Arranger", description: "Rearrange drag-and-drop dashboard widgets", requirement: "Drag & drop widget", xpReward: 100, coinsReward: 10, icon: "🧩", category: "Productivity", tier: "Common", progressNeeded: 1, currentProgress: 0, unlocked: false },
  { id: "p7", title: "Multiple Tellers", description: "Create and hold at least 3 distinct wallets", requirement: "Create 3 wallets", xpReward: 400, coinsReward: 40, icon: "💳", category: "Productivity", tier: "Rare", progressNeeded: 3, currentProgress: 0, unlocked: false },
  { id: "p8", title: "Wallet Transfer", description: "Transfer cash between two wallets", requirement: "Wallet transfer", xpReward: 200, coinsReward: 20, icon: "⇄", category: "Productivity", tier: "Common", progressNeeded: 1, currentProgress: 0, unlocked: false },
  { id: "p9", title: "Subscription Track", description: "Log a recurring service subscription", requirement: "Log subscription", xpReward: 150, coinsReward: 15, icon: "🔁", category: "Productivity", tier: "Common", progressNeeded: 1, currentProgress: 0, unlocked: false },
  { id: "p10", title: "Split Bill Ledger", description: "Create a split bill for restaurant/trips", requirement: "Create split bill", xpReward: 300, coinsReward: 30, icon: "🍕", category: "Productivity", tier: "Rare", progressNeeded: 1, currentProgress: 0, unlocked: false },
  { id: "p11", title: "Settle Up Master", description: "Completely settle a pending split bill", requirement: "Settle Split", xpReward: 500, coinsReward: 50, icon: "🤝", category: "Productivity", tier: "Rare", progressNeeded: 1, currentProgress: 0, unlocked: false },

  // ─── CATEGORY 8: SPECIAL (11 achievements) ───
  { id: "sp1", title: "Profile Ready", description: "Modify your name/phone in profile", requirement: "Update profile settings", xpReward: 100, coinsReward: 10, icon: "👤", category: "Special", tier: "Common", progressNeeded: 1, currentProgress: 0, unlocked: false },
  { id: "sp2", title: "Theme Changer", description: "Switch and save app interface theme", requirement: "Apply new theme", xpReward: 100, coinsReward: 10, icon: "🎨", category: "Special", tier: "Common", progressNeeded: 1, currentProgress: 0, unlocked: false },
  { id: "sp3", title: "Title Equipped", description: "Equip a progress title in achievements page", requirement: "Equip a Title", xpReward: 100, coinsReward: 10, icon: "🎗️", category: "Special", tier: "Common", progressNeeded: 1, currentProgress: 0, unlocked: false },
  { id: "sp4", title: "Avatar Frame", description: "Equip a progress level avatar frame", requirement: "Equip Avatar Frame", xpReward: 150, coinsReward: 15, icon: "🖼️", category: "Special", tier: "Common", progressNeeded: 1, currentProgress: 0, unlocked: false },
  { id: "sp5", title: "Valued Feedback", description: "Submit feedback message to admin desk", requirement: "Submit Feedback", xpReward: 200, coinsReward: 20, icon: "✉️", category: "Special", tier: "Common", progressNeeded: 1, currentProgress: 0, unlocked: false },
  { id: "sp6", title: "PWA Installed", description: "Verify PWA configuration and cache availability", requirement: "Access offline", xpReward: 300, coinsReward: 30, icon: "📲", category: "Special", tier: "Rare", progressNeeded: 1, currentProgress: 0, unlocked: false },
  { id: "sp7", title: "Coin Accumulator", description: "Hold at least 1,000 game coins", requirement: "Accumulate 1,000 coins", xpReward: 300, coinsReward: 30, icon: "🪙", category: "Special", tier: "Common", progressNeeded: 1000, currentProgress: 0, unlocked: false },
  { id: "sp8", title: "Coin Spend Thrift", description: "Spend coins to unlock customization themes", requirement: "Purchase customization", xpReward: 200, coinsReward: 20, icon: "🛒", category: "Special", tier: "Common", progressNeeded: 1, currentProgress: 0, unlocked: false },
  { id: "sp9", title: "Currency Converter", description: "Switch default currency to USD/EUR", requirement: "Switch currency", xpReward: 150, coinsReward: 15, icon: "💱", category: "Special", tier: "Common", progressNeeded: 1, currentProgress: 0, unlocked: false },
  { id: "sp10", title: "Sound On", description: "Trigger audio synthesis clicks 10 times", requirement: "Trigger audio sound fx", xpReward: 100, coinsReward: 10, icon: "🔊", category: "Special", tier: "Common", progressNeeded: 10, currentProgress: 0, unlocked: false },
  { id: "sp11", title: "Streak Champion", description: "Reach a streak higher than 20 days", requirement: "Streak > 20 days", xpReward: 500, coinsReward: 50, icon: "🔥", category: "Special", tier: "Rare", progressNeeded: 20, currentProgress: 0, unlocked: false },

  // ─── CATEGORY 9: LEGENDARY (11 achievements) ───
  { id: "l1", title: "Half-Million Net Worth", description: "Aggregate a Net Worth of ₹5,00,000", requirement: "Net worth ₹5L", xpReward: 2000, coinsReward: 200, icon: "🏛️", category: "Legendary", tier: "Legendary", progressNeeded: 500000, currentProgress: 0, unlocked: false },
  { id: "l2", title: "Millionaire Club", description: "Aggregate a Net Worth of ₹10,00,000", requirement: "Net worth ₹10L", xpReward: 5000, coinsReward: 500, icon: "👑", category: "Legendary", tier: "Legendary", progressNeeded: 1000000, currentProgress: 0, unlocked: false },
  { id: "l3", title: "Level 10 Accomplishment", description: "Ascend past Progression Level 10", requirement: "Reach Level 10", xpReward: 1000, coinsReward: 100, icon: "🎖️", category: "Legendary", tier: "Rare", progressNeeded: 10, currentProgress: 0, unlocked: false },
  { id: "l4", title: "Level 12 Ascent", description: "Ascend past Progression Level 12", requirement: "Reach Level 12", xpReward: 2500, coinsReward: 250, icon: "🛸", category: "Legendary", tier: "Epic", progressNeeded: 12, currentProgress: 0, unlocked: false },
  { id: "l5", title: "Ultimate Wealth God", description: "Ascend to Progression Level 15", requirement: "Reach Level 15", xpReward: 10000, coinsReward: 1000, icon: "🌌", category: "Legendary", tier: "Legendary", progressNeeded: 15, currentProgress: 0, unlocked: false },
  { id: "l6", title: "Perfect Budget Month", description: "Spent exactly within 5% of budget allocations", requirement: "95% budget matching", xpReward: 2000, coinsReward: 200, icon: "🎯", category: "Legendary", tier: "Epic", progressNeeded: 1, currentProgress: 0, unlocked: false },
  { id: "l7", title: "Zero Liability", description: "Pay off remaining balances of all loan accounts", requirement: "Repay all loans", xpReward: 3000, coinsReward: 300, icon: "🛡️", category: "Legendary", tier: "Legendary", progressNeeded: 1, currentProgress: 0, unlocked: false },
  { id: "l8", title: "Financial Freedom", description: "Liquidity balance exceeds yearly subscription sums", requirement: "Free from dues", xpReward: 1500, coinsReward: 150, icon: "🕊️", category: "Legendary", tier: "Rare", progressNeeded: 1, currentProgress: 0, unlocked: false },
  { id: "l9", title: "Grand Collector", description: "Unlock 50 distinct achievements total", requirement: "Settle 50 achievements", xpReward: 5000, coinsReward: 500, icon: "🏆", category: "Legendary", tier: "Legendary", progressNeeded: 50, currentProgress: 0, unlocked: false },
  { id: "l10", title: "Wealth Baron Pro", description: "Hold investments larger than total yearly expenses", requirement: "Portfolio > expenses", xpReward: 3000, coinsReward: 300, icon: "📈", category: "Legendary", tier: "Legendary", progressNeeded: 1, currentProgress: 0, unlocked: false },
  { id: "l11", title: "Legendary Consistency", description: "Log transactions 150 days in a row", requirement: "150d streak", xpReward: 8000, coinsReward: 800, icon: "🔥", category: "Legendary", tier: "Legendary", progressNeeded: 150, currentProgress: 0, unlocked: false },

  // ─── CATEGORY 10: SEASONAL (11 achievements) ───
  { id: "se1", title: "New Year Resolution", description: "Create a savings goal in January", requirement: "Save in Jan", xpReward: 200, coinsReward: 20, icon: "🎆", category: "Seasonal", tier: "Rare", progressNeeded: 1, currentProgress: 0, unlocked: false },
  { id: "se2", title: "Spring Awakening", description: "Audit category variances in March/April", requirement: "Audit in Spring", xpReward: 200, coinsReward: 20, icon: "🌸", category: "Seasonal", tier: "Common", progressNeeded: 1, currentProgress: 0, unlocked: false },
  { id: "se3", title: "Summer Spender", description: "Stay under budget in vacation/leisure", requirement: "Summer budget check", xpReward: 200, coinsReward: 20, icon: "☀️", category: "Seasonal", tier: "Common", progressNeeded: 1, currentProgress: 0, unlocked: false },
  { id: "se4", title: "Monsoon Saver", description: "Deposit to emergency fund in rainy seasons", requirement: "Save in monsoon", xpReward: 200, coinsReward: 20, icon: "🌧️", category: "Seasonal", tier: "Common", progressNeeded: 1, currentProgress: 0, unlocked: false },
  { id: "se5", title: "Autumn Planner", description: "Check investment performances in Oct", requirement: "Portfolio audit Oct", xpReward: 200, coinsReward: 20, icon: "🍁", category: "Seasonal", tier: "Common", progressNeeded: 1, currentProgress: 0, unlocked: false },
  { id: "se6", title: "Winter Warmth", description: "Save money on fuel/transport in Dec", requirement: "Transport save Dec", xpReward: 200, coinsReward: 20, icon: "❄️", category: "Seasonal", tier: "Common", progressNeeded: 1, currentProgress: 0, unlocked: false },
  { id: "se7", title: "Festival Budgeting", description: "Create a seasonal festival budget limit", requirement: "Festival budget block", xpReward: 200, coinsReward: 20, icon: "🪔", category: "Seasonal", tier: "Common", progressNeeded: 1, currentProgress: 0, unlocked: false },
  { id: "se8", title: "Tax Auditor Pro", description: "Review and print reports for tax season (April)", requirement: "Print tax files", xpReward: 300, coinsReward: 30, icon: "📂", category: "Seasonal", tier: "Rare", progressNeeded: 1, currentProgress: 0, unlocked: false },
  { id: "se9", title: "Birthday Treat Split", description: "Settle a split bill on your birthday month", requirement: "Settle birthday split", xpReward: 250, coinsReward: 25, icon: "🎂", category: "Seasonal", tier: "Common", progressNeeded: 1, currentProgress: 0, unlocked: false },
  { id: "se10", title: "Midnight Auditor", description: "Log a transaction between 12:00 AM and 2:00 AM", requirement: "Late night log", xpReward: 150, coinsReward: 15, icon: "🌌", category: "Seasonal", tier: "Common", progressNeeded: 1, currentProgress: 0, unlocked: false },
  { id: "se11", title: "Weekend Warrior Pro", description: "Log 5 transactions on a Saturday", requirement: "Busy Saturday", xpReward: 200, coinsReward: 20, icon: "🚀", category: "Seasonal", tier: "Common", progressNeeded: 5, currentProgress: 0, unlocked: false }
];
