// Progression levels (at least 20)
export const PROGRESSION_LEVELS = [
  { level: 1, name: "Beginner Saver", xpRequired: 0, icon: "🌱", color: "from-green-500 to-emerald-600", reward: "Apprentice Badge & 'Novice' Title" },
  { level: 2, name: "Daily Tracker", xpRequired: 500, icon: "📒", color: "from-blue-500 to-indigo-600", reward: "+50 Coins & 'Tracker' Title" },
  { level: 3, name: "Smart Spender", xpRequired: 1200, icon: "💰", color: "from-emerald-500 to-teal-600", reward: "Copper Avatar Frame & 'Thrifty' Sticker" },
  { level: 4, name: "Budget Builder", xpRequired: 2200, icon: "🧱", color: "from-amber-500 to-yellow-600", reward: "+100 Coins & 'Budgeter' Title" },
  { level: 5, name: "Habit Master", xpRequired: 3500, icon: "🔁", color: "from-orange-500 to-red-600", reward: "Silver Avatar Frame & 'Consistent' Sticker" },
  { level: 6, name: "Frugal Finder", xpRequired: 5000, icon: "🔍", color: "from-violet-500 to-purple-600", reward: "+150 Coins & 'Frugal' Title" },
  { level: 7, name: "Compound Creator", xpRequired: 7000, icon: "📈", color: "from-indigo-500 to-sky-600", reward: "Investment Theme & 'Investor' Badge" },
  { level: 8, name: "Goal Getter", xpRequired: 9500, icon: "🎯", color: "from-rose-500 to-pink-600", reward: "+200 Coins & 'Goal Getter' Title" },
  { level: 9, name: "Expense Auditor", xpRequired: 12500, icon: "🕵️", color: "from-cyan-500 to-teal-600", reward: "Audit Sticker & 'Auditor' Title" },
  { level: 10, name: "Wealth Initiate", xpRequired: 16000, icon: "💎", color: "from-teal-500 to-emerald-600", reward: "Gold Avatar Frame & 'Wealthy' Badge" },
  { level: 11, name: "Carbon Reducer", xpRequired: 20000, icon: "🍃", color: "from-lime-500 to-green-600", reward: "+250 Coins & 'Eco Guardian' Theme" },
  { level: 12, name: "Interest Accumulator", xpRequired: 25000, icon: "🪙", color: "from-yellow-500 to-amber-600", reward: "Interest Calculator Widget & 'Saver Pro' Title" },
  { level: 13, name: "Portfolio Architect", xpRequired: 31000, icon: "📂", color: "from-sky-500 to-blue-600", reward: "Premium Portfolio Theme & 'Architect' Badge" },
  { level: 14, name: "Dividend Baron", xpRequired: 38000, icon: "👑", color: "from-fuchsia-500 to-purple-600", reward: "+300 Coins & 'Baron' Title" },
  { level: 15, name: "Financial Ninja", xpRequired: 46000, icon: "🥷", color: "from-red-500 to-rose-600", reward: "Dark Mode Ninja Theme & Ninja Avatar Frame" },
  { level: 16, name: "Market Wizard", xpRequired: 55000, icon: "🧙", color: "from-purple-500 to-indigo-600", reward: "+500 Coins & 'Wizard' Title" },
  { level: 17, name: "Asset Emperor", xpRequired: 65000, icon: "🏛️", color: "from-amber-600 to-yellow-600", reward: "Platinum Avatar Frame & Asset Badge" },
  { level: 18, name: "Freedom Seeker", xpRequired: 76000, icon: "🕊️", color: "from-slate-500 to-gray-600", reward: "Financial Freedom Dashboard Skin & 'Free' Title" },
  { level: 19, name: "Wealth Tycoon", xpRequired: 88000, icon: "🚀", color: "from-pink-500 to-rose-600", reward: "+1000 Coins & 'Tycoon' Title" },
  { level: 20, name: "Financial Legend", xpRequired: 100000, icon: "👑", color: "from-purple-600 via-pink-500 to-orange-500", reward: "Cosmic Avatar Frame & 'Legend' Title" }
];

// XP rewards for actions
export const XP_ACTIONS = [
  { id: "login", label: "Daily Login", xp: 100, coins: 10 },
  { id: "add_expense", label: "Add Expense", xp: 50, coins: 5 },
  { id: "add_income", label: "Add Income", xp: 50, coins: 5 },
  { id: "upload_receipt", label: "Upload Receipt", xp: 150, coins: 15 },
  { id: "create_budget", label: "Create Budget", xp: 200, coins: 20 },
  { id: "stay_daily_budget", label: "Stay Within Daily Budget", xp: 100, coins: 10 },
  { id: "stay_weekly_budget", label: "Stay Within Weekly Budget", xp: 300, coins: 30 },
  { id: "stay_monthly_budget", label: "Stay Within Monthly Budget", xp: 1000, coins: 100 },
  { id: "complete_review", label: "Complete Monthly Review", xp: 500, coins: 50 },
  { id: "add_goal", label: "Add Savings Goal", xp: 150, coins: 15 },
  { id: "reach_goal", label: "Reach Savings Goal", xp: 1000, coins: 100 },
  { id: "add_investment", label: "Add Investment", xp: 300, coins: 30 },
  { id: "track_bills", label: "Track Bills", xp: 100, coins: 10 },
  { id: "pay_bills_on_time", label: "Pay Bills On Time", xp: 250, coins: 25 },
  { id: "categorize_expense", label: "Categorize Expense", xp: 40, coins: 4 },
  { id: "export_reports", label: "Export Reports", xp: 200, coins: 20 },
  { id: "view_analytics", label: "View Analytics", xp: 75, coins: 7 },
  { id: "maintain_streak", label: "Maintain Daily Streak (+1 Day)", xp: 150, coins: 15 },
  { id: "invite_friends", label: "Invite Friends", xp: 500, coins: 50 },
  { id: "backup_data", label: "Backup Data", xp: 100, coins: 10 }
];

// Achievements (at least 20)
export const INITIAL_ACHIEVEMENTS = [
  {
    id: "ach_first_expense",
    title: "First Expense",
    description: "Logged your first expense transaction",
    requirement: "Add 1 expense",
    xpReward: 100,
    coinsReward: 10,
    icon: "💸",
    category: "Savings",
    tier: "Common",
    theme: "from-blue-500/20 to-indigo-500/10 border-blue-500/30 text-blue-400",
    unlocked: true,
    progressNeeded: 1,
    currentProgress: 1,
    rewardsText: "Title: 'Beginner' • sticker: 'Piggy Bank'"
  },
  {
    id: "ach_first_income",
    title: "First Income",
    description: "Logged your first income transaction",
    requirement: "Add 1 income",
    xpReward: 100,
    coinsReward: 10,
    icon: "💰",
    category: "Savings",
    tier: "Common",
    theme: "from-green-500/20 to-emerald-500/10 border-green-500/30 text-green-400",
    unlocked: true,
    progressNeeded: 1,
    currentProgress: 1,
    rewardsText: "Sticker: 'Coin Burst' • +10 Coins"
  },
  {
    id: "ach_first_budget",
    title: "First Budget",
    description: "Set up a monthly category budget limit",
    requirement: "Create 1 budget",
    xpReward: 150,
    coinsReward: 15,
    icon: "🧱",
    category: "Budget",
    tier: "Common",
    theme: "from-amber-500/20 to-yellow-500/10 border-amber-500/30 text-amber-400",
    unlocked: true,
    progressNeeded: 1,
    currentProgress: 1,
    rewardsText: "Title: 'Planner' • Profile Badge: 'Architect'"
  },
  {
    id: "ach_budget_master",
    title: "Budget Master",
    description: "Keep actual expenses below budget for 3 consecutive months",
    requirement: "Stay in budget for 3 months",
    xpReward: 1000,
    coinsReward: 100,
    icon: "👑",
    category: "Budget",
    tier: "Epic",
    theme: "from-purple-500/20 to-pink-500/10 border-purple-500/30 text-purple-400",
    unlocked: false,
    progressNeeded: 3,
    currentProgress: 0,
    rewardsText: "Theme: 'Royal Velvet' • Avatar Frame: 'Gold Filigree'"
  },
  {
    id: "ach_budget_guardian",
    title: "Budget Guardian",
    description: "Do not exceed budget in any category for a full month",
    requirement: "Stay in budget for 1 full month",
    xpReward: 500,
    coinsReward: 50,
    icon: "🛡️",
    category: "Budget",
    tier: "Rare",
    theme: "from-cyan-500/20 to-blue-500/10 border-cyan-500/30 text-cyan-400",
    unlocked: false,
    progressNeeded: 1,
    currentProgress: 0,
    rewardsText: "Title: 'Guardian' • Profile Badge: 'Safe Shield'"
  },
  {
    id: "ach_daily_tracker",
    title: "Daily Tracker",
    description: "Log transactions 3 days in a row",
    requirement: "Add transaction 3 days in a row",
    xpReward: 200,
    coinsReward: 20,
    icon: "🔥",
    category: "Streaks",
    tier: "Common",
    theme: "from-orange-500/20 to-red-500/10 border-orange-500/30 text-orange-400",
    unlocked: true,
    progressNeeded: 3,
    currentProgress: 3,
    rewardsText: "Sticker: 'Flame Icon' • +20 Coins"
  },
  {
    id: "ach_seven_day",
    title: "7-Day Streak",
    description: "Keep a 7-day login/logging streak",
    requirement: "Maintain streak for 7 days",
    xpReward: 500,
    coinsReward: 50,
    icon: "⚡",
    category: "Streaks",
    tier: "Rare",
    theme: "from-indigo-500/20 to-purple-500/10 border-indigo-500/30 text-indigo-400",
    unlocked: true,
    progressNeeded: 7,
    currentProgress: 7,
    rewardsText: "Title: 'Disciplined' • Sticker: 'Lighting Spark'"
  },
  {
    id: "ach_thirty_day",
    title: "30-Day Streak",
    description: "Keep a 30-day login/logging streak",
    requirement: "Maintain streak for 30 days",
    xpReward: 1500,
    coinsReward: 150,
    icon: "📅",
    category: "Streaks",
    tier: "Epic",
    theme: "from-rose-500/20 to-pink-500/10 border-rose-500/30 text-rose-400",
    unlocked: false,
    progressNeeded: 30,
    currentProgress: 18,
    rewardsText: "Avatar Frame: 'Chronos Silver' • Theme: 'Neon Amber'"
  },
  {
    id: "ach_hundred_day",
    title: "100-Day Streak",
    description: "Keep a 100-day logging streak",
    requirement: "Maintain streak for 100 days",
    xpReward: 5000,
    coinsReward: 500,
    icon: "💯",
    category: "Streaks",
    tier: "Legendary",
    theme: "from-yellow-500/20 to-amber-500/10 border-yellow-500/30 text-yellow-400",
    unlocked: false,
    progressNeeded: 100,
    currentProgress: 18,
    rewardsText: "Title: 'Immortal Tracker' • Badge: 'Eternal Flame'"
  },
  {
    id: "ach_savings_champ",
    title: "Savings Champion",
    description: "Save 50% or more of your total monthly income",
    requirement: "Monthly savings rate >= 50%",
    xpReward: 800,
    coinsReward: 80,
    icon: "🏆",
    category: "Savings",
    tier: "Rare",
    theme: "from-emerald-500/20 to-green-500/10 border-emerald-500/30 text-emerald-400",
    unlocked: false,
    progressNeeded: 1,
    currentProgress: 0,
    rewardsText: "Title: 'Frugal King' • Profile Badge: 'Trophy'"
  },
  {
    id: "ach_ten_k_saved",
    title: "₹10,000 Saved",
    description: "Accumulate total savings of ₹10,000",
    requirement: "Total savings reach ₹10,000",
    xpReward: 300,
    coinsReward: 30,
    icon: "🥈",
    category: "Savings",
    tier: "Common",
    theme: "from-slate-400/20 to-gray-500/10 border-slate-400/30 text-slate-300",
    unlocked: true,
    progressNeeded: 10000,
    currentProgress: 10000,
    rewardsText: "Sticker: 'Silver Stack' • +30 Coins"
  },
  {
    id: "ach_fifty_k_saved",
    title: "₹50,000 Saved",
    description: "Accumulate total savings of ₹50,000",
    requirement: "Total savings reach ₹50,000",
    xpReward: 1000,
    coinsReward: 100,
    icon: "🥇",
    category: "Savings",
    tier: "Rare",
    theme: "from-amber-400/20 to-yellow-500/10 border-amber-400/30 text-amber-300",
    unlocked: false,
    progressNeeded: 50000,
    currentProgress: 15400,
    rewardsText: "Title: 'Accumulator' • Badge: 'Gold Medal'"
  },
  {
    id: "ach_no_spend_day",
    title: "No Spend Day",
    description: "Go an entire day without logging any expenses",
    requirement: "Have a day with ₹0 expenses",
    xpReward: 200,
    coinsReward: 20,
    icon: "❌",
    category: "Savings",
    tier: "Common",
    theme: "from-red-500/20 to-rose-500/10 border-red-500/30 text-red-400",
    unlocked: true,
    progressNeeded: 1,
    currentProgress: 1,
    rewardsText: "Sticker: 'Zero Barrier' • +20 Coins"
  },
  {
    id: "ach_no_spend_week",
    title: "No Spend Week",
    description: "Go 7 consecutive days spending only on essentials",
    requirement: "7 days essentials only",
    xpReward: 1200,
    coinsReward: 120,
    icon: "🧘",
    category: "Savings",
    tier: "Epic",
    theme: "from-violet-500/20 to-fuchsia-500/10 border-violet-500/30 text-violet-400",
    unlocked: false,
    progressNeeded: 1,
    currentProgress: 0,
    rewardsText: "Title: 'Zen Master' • Theme: 'Monochrome Calm'"
  },
  {
    id: "ach_expense_explorer",
    title: "Expense Explorer",
    description: "Log expenses in 5 different categories",
    requirement: "Use 5 unique expense categories",
    xpReward: 250,
    coinsReward: 25,
    icon: "🗺️",
    category: "Budget",
    tier: "Common",
    theme: "from-teal-500/20 to-cyan-500/10 border-teal-500/30 text-teal-400",
    unlocked: true,
    progressNeeded: 5,
    currentProgress: 5,
    rewardsText: "Sticker: 'Compass' • Profile Badge: 'Explorer'"
  },
  {
    id: "ach_category_expert",
    title: "Category Expert",
    description: "Log expenses in 10 different categories",
    requirement: "Use 10 unique expense categories",
    xpReward: 600,
    coinsReward: 60,
    icon: "🧠",
    category: "Budget",
    tier: "Rare",
    theme: "from-blue-600/20 to-cyan-600/10 border-blue-600/30 text-blue-300",
    unlocked: false,
    progressNeeded: 10,
    currentProgress: 6,
    rewardsText: "Title: 'Categorizer Pro' • +60 Coins"
  },
  {
    id: "ach_analytics_lover",
    title: "Analytics Lover",
    description: "Open reports and check analysis charts 5 times",
    requirement: "View reports 5 times",
    xpReward: 150,
    coinsReward: 15,
    icon: "📊",
    category: "Special Events",
    tier: "Common",
    theme: "from-violet-400/20 to-purple-500/10 border-violet-400/30 text-violet-300",
    unlocked: true,
    progressNeeded: 5,
    currentProgress: 5,
    rewardsText: "Sticker: 'Bar Chart' • +15 Coins"
  },
  {
    id: "ach_receipt_collector",
    title: "Receipt Collector",
    description: "Upload 10 receipt images using OCR",
    requirement: "Process 10 receipts with OCR scan tool",
    xpReward: 400,
    coinsReward: 40,
    icon: "🧾",
    category: "Special Events",
    tier: "Common",
    theme: "from-sky-500/20 to-indigo-500/10 border-sky-500/30 text-sky-400",
    unlocked: false,
    progressNeeded: 10,
    currentProgress: 4,
    rewardsText: "Title: 'Paperless' • Sticker: 'Scan Success'"
  },
  {
    id: "ach_investment_starter",
    title: "Investment Starter",
    description: "Log your first investment transaction",
    requirement: "Add an investment transaction of >= ₹1,000",
    xpReward: 300,
    coinsReward: 30,
    icon: "🌱",
    category: "Investments",
    tier: "Common",
    theme: "from-emerald-600/20 to-teal-600/10 border-emerald-600/30 text-emerald-400",
    unlocked: true,
    progressNeeded: 1000,
    currentProgress: 120000, // already has Nifty fund
    rewardsText: "Title: 'Seed Sower' • +30 Coins"
  },
  {
    id: "ach_mutual_fund",
    title: "Mutual Fund Investor",
    description: "Log mutual fund assets totaling ₹20,000",
    requirement: "Mutual fund assets reach ₹20,000",
    xpReward: 800,
    coinsReward: 80,
    icon: "📈",
    category: "Investments",
    tier: "Rare",
    theme: "from-green-600/20 to-emerald-600/10 border-green-600/30 text-green-300",
    unlocked: true,
    progressNeeded: 20000,
    currentProgress: 120000, // already has Nifty fund
    rewardsText: "Title: 'Fund Fanatic' • Profile Badge: 'Bull Market'"
  },
  {
    id: "ach_emergency_fund",
    title: "Emergency Fund Builder",
    description: "Save 3 months worth of living expenses (₹30,000)",
    requirement: "Save ₹30,000 in emergency fund",
    xpReward: 2000,
    coinsReward: 200,
    icon: "🚨",
    category: "Savings",
    tier: "Epic",
    theme: "from-rose-600/20 to-red-600/10 border-rose-600/30 text-rose-400",
    unlocked: false,
    progressNeeded: 30000,
    currentProgress: 5000,
    rewardsText: "Avatar Frame: 'Life Preserver' • Title: 'Safe & Sound'"
  },
  {
    id: "ach_debt_destroyer",
    title: "Debt Destroyer",
    description: "Mark a debt category transaction as paid",
    requirement: "Pay off 1 debt transaction",
    xpReward: 1000,
    coinsReward: 100,
    icon: "🔨",
    category: "Special Events",
    tier: "Rare",
    theme: "from-red-700/20 to-rose-700/10 border-red-700/30 text-red-300",
    unlocked: false,
    progressNeeded: 1,
    currentProgress: 0,
    rewardsText: "Title: 'Unshackled' • Sticker: 'Broken Chain'"
  },
  {
    id: "ach_bill_hero",
    title: "Bill Payment Hero",
    description: "Pay 5 utility bills within their due dates",
    requirement: "Pay 5 bills on time",
    xpReward: 500,
    coinsReward: 50,
    icon: "🦸",
    category: "Special Events",
    tier: "Common",
    theme: "from-blue-400/20 to-indigo-500/10 border-blue-400/30 text-blue-300",
    unlocked: true,
    progressNeeded: 5,
    currentProgress: 5,
    rewardsText: "Title: 'Punctual' • Profile Badge: 'Clockwork'"
  },
  {
    id: "ach_smart_shopper",
    title: "Smart Shopper",
    description: "Dining category total under ₹500 for 7 consecutive days",
    requirement: "Spend under ₹500 on dining for a week",
    xpReward: 400,
    coinsReward: 40,
    icon: "🛒",
    category: "Special Events",
    tier: "Common",
    theme: "from-amber-600/20 to-orange-600/10 border-amber-600/30 text-amber-400",
    unlocked: false,
    progressNeeded: 500,
    currentProgress: 0,
    rewardsText: "Sticker: 'Smart Cart' • +40 Coins"
  },
  {
    id: "ach_tax_planner",
    title: "Tax Planner",
    description: "Log a transaction in tax savings category",
    requirement: "Log tax saving investment",
    xpReward: 750,
    coinsReward: 75,
    icon: "📝",
    category: "Investments",
    tier: "Rare",
    theme: "from-violet-700/20 to-purple-800/10 border-violet-700/30 text-violet-300",
    unlocked: false,
    progressNeeded: 1,
    currentProgress: 0,
    rewardsText: "Title: 'Strategist' • Profile Badge: 'Shield Pen'"
  },
  {
    id: "ach_wealth_builder",
    title: "Wealth Builder",
    description: "Reach total net worth of ₹1,00,000 in your assets",
    requirement: "Total asset value >= ₹1,00,000",
    xpReward: 2500,
    coinsReward: 250,
    icon: "💎",
    category: "Investments",
    tier: "Epic",
    theme: "from-cyan-400/20 to-teal-500/10 border-cyan-400/30 text-cyan-300",
    unlocked: true,
    progressNeeded: 100000,
    currentProgress: 200000, // wealth tracker is 200,000
    rewardsText: "Theme: 'Diamond Glow' • Avatar Frame: 'Diamond Crest'"
  },
  {
    id: "ach_financial_legend",
    title: "Financial Legend",
    description: "Reach level 10 and obtain 20 badges",
    requirement: "Lvl 10 + 20 unlocked badges",
    xpReward: 10000,
    coinsReward: 1000,
    icon: "👑",
    category: "Special Events",
    tier: "Legendary",
    theme: "from-yellow-400 via-pink-500 to-purple-600 border-yellow-500/50 text-white font-extrabold shadow-lg shadow-yellow-500/10 animate-pulse",
    unlocked: false,
    progressNeeded: 20,
    currentProgress: 13, // 13 currently unlocked
    rewardsText: "Title: 'Financial Deity' • Badge: 'Crown of Glory' • Theme: 'Celestial Space'"
  }
];

export const MOCK_LEADERBOARD = [
  { rank: 1, username: "Kabir Mehta", level: 12, xp: 24500, achievements: 22, coins: 2150, avatar: "K", color: "from-yellow-500 to-amber-600", self: false },
  { rank: 2, username: "You (Aditya)", level: 4, xp: 3450, achievements: 13, coins: 640, avatar: "A", color: "from-indigo-500 to-blue-600", self: true },
  { rank: 3, username: "Sarah (Spouse)", level: 3, xp: 1850, achievements: 8, coins: 410, avatar: "S", color: "from-pink-500 to-purple-500", self: false },
  { rank: 4, username: "Rohan Das", level: 3, xp: 1450, achievements: 7, coins: 380, avatar: "R", color: "from-emerald-500 to-teal-600", self: false },
  { rank: 5, username: "Neha Sharma", level: 2, xp: 950, achievements: 5, coins: 220, avatar: "N", color: "from-cyan-500 to-blue-500", self: false },
  { rank: 6, username: "Leo (Son)", level: 1, xp: 320, achievements: 3, coins: 90, avatar: "L", color: "from-amber-500 to-orange-500", self: false }
];
